services:
  bank-data:
    image: postgres:15-alpine
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bank"]
      interval: 5s
      timeout: 5s
      retries: 5
  bank:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOGGING_FILE_PATH=/app/logs
      - SECRET_CARD_NUMBER_KEY=${SECRET_CARD_NUMBER_KEY}
      - HASH_SECRET_KEY=${HASH_SECRET_KEY}
      - JWT_DIRECTORY_PATH=${JWT_DIRECTORY_PATH}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONT_URL=${FRONT_URL}
    volumes:
      - ./jwt:/app/jwt
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      bank-data:
        condition: service_healthy

volumes:
  postgres-data: