spring:
  application:
    name: Bank_REST_Test_Task
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
jasypt:
  encryptor:
    password: "${SECRET_CARD_NUMBER_KEY}"
    algorithm: PBEWITHHMACSHA512ANDAES_256
payment:
  card:
    tokenization:
      hash-key: "${HASH_SECRET_KEY}"
jwt:
  access:
    expiration: 3600000
  refresh:
    expiration: 1209600000
  keys:
    path: "${JWT_DIRECTORY_PATH}"
cors:
  allowed-origins: "${FRONT_URL}"

